import type { PlaceListItem } from './places';

/**
 * API erişilemediğinde (ör. backend çalışmıyorken Expo demo) kullanılan örnek veri.
 * apps/api/prisma/seed.ts içeriğiyle aynıdır.
 */
export const MOCK_PLACES: PlaceListItem[] = [
  {
    id: 'mock-1',
    name: 'Çıralı Sahil Kamp Alanı',
    slug: 'cirali-sahil-kamp-alani',
    city: 'Antalya',
    region: 'Akdeniz',
    latitude: 36.4139,
    longitude: 30.4762,
    locationPrecision: 'EXACT',
    approximateRadiusMeters: null,
    feeType: 'PAID',
    operatingStatus: 'OPEN',
    primaryActivity: 'CARAVAN',
    activities: ['CARAVAN', 'TENT', 'BARBECUE'],
    photoStatus: 'PENDING',
    score: { overall: 4.4, features: 4.4, userRating: 4.6, atmosphere: 4.1 },
  },
  {
    id: 'mock-2',
    name: 'Abant Gölü Piknik Alanı',
    slug: 'abant-golu-piknik-alani',
    city: 'Bolu',
    region: 'Karadeniz',
    latitude: 40.6068,
    longitude: 31.2792,
    locationPrecision: 'EXACT',
    approximateRadiusMeters: null,
    feeType: 'PAID',
    operatingStatus: 'OPEN',
    primaryActivity: 'PICNIC',
    activities: ['PICNIC', 'BARBECUE'],
    photoStatus: 'PENDING',
    score: { overall: 4, features: 4, userRating: 4.2, atmosphere: 3.6 },
  },
  {
    id: 'mock-3',
    name: 'Kazdağı Orman Kampı',
    slug: 'kazdagi-orman-kampi',
    city: 'Balıkesir',
    region: 'Marmara',
    latitude: 39.707983,
    longitude: 26.87098,
    locationPrecision: 'APPROXIMATE',
    approximateRadiusMeters: 500,
    feeType: 'FREE',
    operatingStatus: 'OPEN',
    primaryActivity: 'TENT',
    activities: ['TENT'],
    photoStatus: 'PENDING',
    score: { overall: 3.9, features: 2.8, userRating: 4.8, atmosphere: 4.7 },
  },
  {
    id: 'mock-4',
    name: 'Salda Gölü Kamp Noktası',
    slug: 'salda-golu-kamp-noktasi',
    city: 'Burdur',
    region: 'Akdeniz',
    latitude: 37.5417,
    longitude: 29.6708,
    locationPrecision: 'EXACT',
    approximateRadiusMeters: null,
    feeType: 'FREE',
    operatingStatus: 'OPEN',
    primaryActivity: 'CARAVAN',
    activities: ['CARAVAN', 'TENT', 'PICNIC'],
    photoStatus: 'PENDING',
    score: { overall: 4, features: 3.4, userRating: 4.5, atmosphere: 4.3 },
  },
  {
    id: 'mock-5',
    name: 'Uzungöl Karavan Parkı',
    slug: 'uzungol-karavan-parki',
    city: 'Trabzon',
    region: 'Karadeniz',
    latitude: 40.6193,
    longitude: 40.2946,
    locationPrecision: 'EXACT',
    approximateRadiusMeters: null,
    feeType: 'PAID',
    operatingStatus: 'OPEN',
    primaryActivity: 'CARAVAN',
    activities: ['CARAVAN'],
    photoStatus: 'PENDING',
    score: { overall: 4.2, features: 4.7, userRating: 4, atmosphere: 3.2 },
  },
  {
    id: 'mock-6',
    name: 'Kapadokya Vadi Kampı',
    slug: 'kapadokya-vadi-kampi',
    city: 'Nevşehir',
    region: 'İç Anadolu',
    latitude: 38.6431,
    longitude: 34.8289,
    locationPrecision: 'EXACT',
    approximateRadiusMeters: null,
    feeType: 'PAID',
    operatingStatus: 'SEASONAL',
    primaryActivity: 'CARAVAN',
    activities: ['CARAVAN', 'TENT', 'BARBECUE'],
    photoStatus: 'PENDING',
    score: { overall: 4.3, features: 4.3, userRating: 4.4, atmosphere: 3.9 },
  },
  {
    id: 'mock-7',
    name: 'Belgrad Ormanı Piknik Sahası',
    slug: 'belgrad-ormani-piknik-sahasi',
    city: 'İstanbul',
    region: 'Marmara',
    latitude: 41.1839,
    longitude: 28.9852,
    locationPrecision: 'EXACT',
    approximateRadiusMeters: null,
    feeType: 'FREE',
    operatingStatus: 'TEMPORARILY_CLOSED',
    primaryActivity: 'PICNIC',
    activities: ['PICNIC', 'BARBECUE'],
    photoStatus: 'PENDING',
    score: { overall: 3.7, features: 3.8, userRating: 3.9, atmosphere: 2.9 },
  },
];
